server:
  port: 9898
spring:
  datasource: # 数据源的相关配置
    #type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver          # mysql驱动
    url: jdbc:mysql://8.137.39.241:4508/rocket-mq?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: XSJroot123456
    hikari:
      connection-timeout: 30000        # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                  # 最小连接数
      maximum-pool-size: 20            # 最大连接数
      auto-commit: true                # 事务自动提交
      idle-timeout: 600000             # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP     # 连接池名字
      max-lifetime: 1800000             # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1  # 连接测试语句

  application:
    name: rocket-mq

rocketmq:
  enhance:
  # 启动隔离，用于激活配置类EnvironmentIsolationConfig
  # 启动后会自动在topic上拼接激活的配置文件，达到自动隔离的效果
  enabledIsolation: true
  # 隔离环境名称，拼接到topic后，topic_dev，默认空字符串
  environment: dev
  name-server: 8.137.39.241:9876 # RocketMQ地址
  producer:
    send-message-timeout: 30000
    group: my-group
#  consumer:
#    consumerGroup: string_consumer
#    stringTopic: string-topic
#    userTopic: user-topic
#    tag: test
#logging:
#  level:
#    RocketmqClient: ERROR
#    io:
#      netty: ERROR